name: Generate Minimal Sitemap

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests to the 'main' branch

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow write access for this workflow only

    steps:
      # Step 1: Check out the repository with sparse checkout enabled
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full Git history
          sparse-checkout: "sitemap.xml"  # Only allow modifications to sitemap.xml

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Use the latest LTS version of Node.js

      # Step 3: Install Sitemap Generator CLI
      - name: Install Sitemap Generator
        run: npm install -g sitemap-generator-cli@2.5.2  # Pin a specific version

      # Step 4: Generate Minimal Sitemap
      - name: Generate Sitemap
        run: |
          sitemap-generator https://republicoframona.github.io/ -o ./sitemap.xml
          sed -i '/<lastmod>/d' sitemap.xml  # Remove <lastmod> tags
          sed -i '/<priority>/d' sitemap.xml  # Remove <priority> tags

      # Step 5: Configure Git for Commit
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Step 6: Commit and Push the Updated Sitemap
      - name: Commit and Push Sitemap
        run: |
          git add sitemap.xml
          git diff --cached --exit-code || git commit -m "Automatically updated sitemap.xml"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
